BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "customer" (
	"id"	INTEGER NOT NULL,
	"surname"	TEXT NOT NULL,
	"name"	TEXT NOT NULL,
	"num_phone"	INTEGER NOT NULL,
	"id_avto"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "services" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL,
	"price"	REAL NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "avto" (
	"id"	INTEGER NOT NULL,
	"model"	TEXT NOT NULL,
	"marka"	TEXT NOT NULL,
	"color"	TEXT NOT NULL,
	"year_build"	TEXT NOT NULL,
	"number"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ord" (
	"id"	INTEGER NOT NULL,
	"id_customer"	INTEGER NOT NULL,
	"id_services"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("id_customer") REFERENCES "customer"("id"),
	FOREIGN KEY("id_services") REFERENCES "services"("id")
);
COMMIT;
